---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ejbca-issuer.keyfactor.com
  resources:
  - clusterissuers
  - issuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ejbca-issuer.keyfactor.com
  resources:
  - clusterissuers/status
  - issuers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ejbca-issuer.keyfactor.com
  resources:
  - issuers/finalizers
  verbs:
  - update
