apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if .Values.secretConfig.useClusterRoleForSecretAccess }}ClusterRole{{ else }}Role{{ end }}
metadata:
  labels:
    {{- include "ejbca-cert-manager-issuer.labels" . | nindent 4 }}
  name: {{ include "ejbca-cert-manager-issuer.name" . }}-secret-reader-role
{{- if not .Values.secretConfig.useClusterRoleForSecretAccess }}
  namespace: {{ .Release.Namespace }}
{{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if .Values.secretConfig.useClusterRoleForSecretAccess }}ClusterRoleBinding{{ else }}RoleBinding{{ end }}
metadata:
  labels:
    {{- include "ejbca-cert-manager-issuer.labels" . | nindent 4 }}
  name: {{ include "ejbca-cert-manager-issuer.name" . }}-secret-reader-rolebinding
{{- if not .Values.secretConfig.useClusterRoleForSecretAccess }}
  namespace: {{ .Release.Namespace }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if .Values.secretConfig.useClusterRoleForSecretAccess }}ClusterRole{{ else }}Role{{ end }}
  name: {{ include "ejbca-cert-manager-issuer.name" . }}-secret-reader-role
subjects:
  - kind: ServiceAccount
    name: {{ include "ejbca-cert-manager-issuer.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}